name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Archive build
      run: mkdir /tmp/github-actions/ && tar -cvf /tmp/github-actions/build.tar ./
    - name: rsync prod
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude=".env" --exclude="node_modules" --exclude="storage" --include="" --filter=""
        path: ./
        remote_path: /var/www/html/laraops/
        remote_host: 161.35.202.88
        remote_user: root
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - name: Execute commands on server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /var/www/html/laraops && php artisan down && php artisan migrate --no-interaction && php artisan up
        host: 161.35.202.88
        username: root
        privateKey: ${{ secrets.DEPLOY_KEY }}
